spring:
  application:
    name: aop
  datasource:
    primary:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.1.102:3306/test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.1.102:3306/test1?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
debug: false